# Settings for the app
app:
  # HTML Title
  title: Stomping Ground | Imagine New Haven
  # Header name
  name: Imagine New Haven
  # Small text below the name
  subname: What would make your neighborhood a better, healthier place to live?
  # Meta description that will show up in Google search results
  meta_description: Create maps of a better, healthier New Haven. Powered by Stomping Ground, by OpenPlans.
  # Home page description
  description: What would you add to your neighborhood to make it a better, healthier place to live? Create a map that shows where you'd like to see improvements, and share the design!
